default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  port: 5432
  password: password
  username: postgres

development:
  <<: *default
  database: tiny_url_development

test:
  <<: *default
  database: tiny_url_test